### ISSUE TITLE
Facing issue in HR/Payroll Copilot application in Azure

### ISSUE THREAD

**Issue by shashankms9** [microsoft/OpenAIWorkshop#158]
Hi @james-tn we are facing an issue in HR/Payroll Copilot application in Azure, after creating the web app we have encountered an issue
ModuleNotFoundError: No module named 'openai.embeddings_utils'

we were able to resolve this issue after installing OpenAI 0.28 package, we were able to view the interface but when we try to enter an example question it is throwing an issue 

APIRemovedInV1: You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28` A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
Traceback:
File "/tmp/8dbecead775ee88/antenv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/tmp/8dbecead775ee88/hr_copilot.py", line 79, in <module>
    stream_out, query_used, history, agent_response = hr_agent.run(user_input=user_input, conversation=history, stream=True)
File "/tmp/8dbecead775ee88/utils.py", line 234, in run
    response = openai.ChatCompletion.create(
File "/tmp/8dbecead775ee88/antenv/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__
File "/tmp/8dbecead775ee88/antenv/lib/python3.10/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__
File "/tmp/8dbecead775ee88/antenv/lib/python3.10/site-packages/openai/lib/_old_api.py", line 33, in __load__

please find the image for references 

![image](https://github.com/microsoft/OpenAIWorkshop/assets/104433795/6cd75d38-1536-488b-804e-4c3d7487f26c)

![image](https://github.com/microsoft/OpenAIWorkshop/assets/104433795/6a82d765-ec2a-42f9-8626-2413cbdd0831)

**Comment by james-tn** [comment]
Looks like you still have the later version of openai library (they recently changed the API). 
Can you update the requirement file to fix openai to 0.28?
Like this
streamlit
openai==0.28.0
streamlit-extras
python-dotenv 
plotly
scipy
scikit-learn
azure-search-documents==11.4.0b9
faiss-cpu

**Comment by shashankms9** [comment]
hi @james-tn thank you for your help issue has been fixed after updating the requirement file in scenarios/incubations/copilot/employee_support/requirements.txt
